### ISSUE TITLE
Python NLTK.download is blocked by BL firewall it seems

### ISSUE THREAD

**Issue by benosteen** [BL-Labs/meetingsparser#2]
Will manually install the Stanford parser inside the repository,

**Comment by knavickas** [comment]
Thanks again for letting me know about this Ben. Once you've tried, do let me know and give me some tips/help links, so I can start learning how to use this too (rather than being lost like a lemon...)

Katrina

Dr Katrina Navickas
Senior Lecturer in History,
School of Humanities Research Students' Tutor,
University of Hertfordshire,
De Havilland Campus, Hatfield, Herts, AL10 9AB.
01707 285624

http://about.me/katrina.navickas
